lib/transformer_utils.dart

`stringLiteral` and `getSpan` were not being exported by `transformer_utils.dart`. In order to use them you have to import files from within `lib/src`.
- Export `text_util.dart` and show `stringLiteral`.
- Include `getSpan` in what to show from `transformed_source_file.dart`.
- Removed `getLiteralValue` from what is shown from `analyzer_helpers.dart`
- `getLiteralValue` does not exist.
- Verify `stringLiteral` and `getSpan` are being exported from `transformer_utils.dart`.
FYA: @greglittlefield-wf @evanweible-wf

UIP-1349 - Export stringLiteral and getSpan

---

pubspec.yaml
smithy.yaml

`analyzer` was being bound to <0.28.0, we should widen that constraint to allow <0.30.0.
- Widen the `analyzer` version constraint
- Verify tests still pass
- None expected
---
FYA: @greglittlefield-wf @evanweible-wf

UIP-1906 Widen version constraints

---

pubspec.yaml

This reverts commit 9c877d46d7676ac21503c9be980d1db0a7abdcde, which was accidentally pushed to master.

UIP-2263 Revert "Bump analyzer constraint"

---

pubspec.yaml

__This patch release includes the following changes:__
- https://github.com/Workiva/dart_transformer_utils/pull/13/commits/15c6e6f58682363e1bb59819b52dabd09bc4883d analyzer `>=0.27.0 <0.31.0` (was `>=0.27.0 <0.30.0`) ([UIP-2288](https://jira.atl.workiva.net/browse/UIP-2288))

UIP-1958 Release dart_transformer_utils 0.1.3

---

Dockerfile

The following pull request has been created by App Frameworks to help move consumers to the latest Smithy image. This was done because of an issue with Dartium and Content-Shell that would fail your CIs. Please seethis [Wiki Question](https://wiki.atl.workiva.net/cq/viewquestion.action?id=96308901&answerId=96308907)for additional context.
The following changes have been made:
* All instances of the production Smithy image have been updated to `drydock-prod.workiva.net/workiva/smithy-runner-generator:355624`.
If you have any questions, please reach out to us in the Support:H5 / Dart Hipchat room

af_new_drydock_image

---

pubspec.yaml

Allow newer versions of `analyzer` that will resolve when running `pub get` on Dart 2.
@Workiva/app-frameworks

Update analyzer version range

---

.gitignore
lib/src/transformed_source_file.dart
pubspec.yaml

transformer_utils had two instances of Dart 1-only constants from `dart:convert` for `HtmlEscapeMode`.
Use the `dart2_constant` library.

Use dart2_constant for HtmlEscapeMode constants

---

pubspec.yaml

Pulls Included in Release:
* [Use dart2_constant for HtmlEscapeMode constants](https://github.com/Workiva/dart_transformer_utils/pull/23)
Requested by: @maxpeterson-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_transformer_utils/compare/0.1.4...Workiva:release_dart_transformer_utils_0_1_5
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_transformer_utils/compare/0.1.4...0.1.5
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/5977371284340736/logs/)

AF-1897 Release dart_transformer_utils 0.1.5

---

pubspec.yaml

Upgrade the `analyzer` dependency to at least `0.35.0`. This will help unblock consumption of the latest `build_*` packages.
@greglittlefield-wf @corwinsheahan-wf

CPLAT-5154: Upgrade to analyzer ^0.35.0

---

pubspec.yaml

Some of the latest build_* packages have started requiring at least analyzer 0.36.0. I tried it out locally by upgrading to analyzer 0.36.3, and all tests still pass.
@greglittlefield-wf @corwinsheahan-wf

CPLAT-6158: Widen analyzer range to include 0.36.x

---

pubspec.yaml

Pull Requests included in release:
* Patch changes:
* [CPLAT-6158: Widen analyzer range to include 0.36.x](https://github.com/Workiva/dart_transformer_utils/pull/33)
Requested by: @evanweible-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_transformer_utils/compare/0.2.1...Workiva:release_dart_transformer_utils_0.2.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_transformer_utils/compare/0.2.1...0.2.2
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/5977371284340736/logs/)

CPLAT-5162 Release dart_transformer_utils 0.2.2

---

pubspec.yaml

Upper bounds of the `analyzer` version need to be increased so that we aren't prevented from pulling newer versions of packages (e.g., `build_web_compilers`) that depend on newer versions of `analyzer`.
Please review @aaronlademann-wf @greglittlefield-wf @kealjones-wk @sydneyjodon-wk

CPLAT-7677 Open analyzer range

---

pubspec.yaml

To unlock the latest analyzer package version, as well as the latest versions of many packages that depend on it, including build packages, we need to widen the version range for this package.
Widen version range to allow analyzer 0.41.x, the latest minor version.
No other changes were necessary
Verify locally that there are no analysis issues in this repo when using analyzer 0.41.x
Unfortunately, Dart 2.7.2 (which is what we use in CI) still can't resolve to this latest analyzer version due to SDK dependency constraints on this `build` package, so this has to be tested locally, with an SDK of at least Dart 2.9.
Also, with the constraint as-is, a `pub upgrade analyzer` for some reason won't resolve this version automatically, but you can force it to resolve to analyzer 0.41.x by …

Widen analyzer range to include 0.41.x

---

Dockerfile

This PR updates the Dockerfile and skynet.yaml for each Dart repo to use 
Dart 2.13 versions of the base docker images (at this point these will be 
wip base images) to verify that full CI checks will pass when using Dart 2.13.
---
This PR was created automatically from a Sourcegraph batch change.
This PR is just a test and should not be merged
Please reach out to #support-client-plat with any questions.
[_Created by Sourcegraph batch change `Workiva/dart_213_test`._](https://sourcegraph.wk-dev.wdesk.org/organizations/Workiva/batch-changes/dart_213_test)

Upgrade to Dart 2.13

---

docs.yml

https://jira.atl.workiva.net/browse/DE-552
As part of, 
[Dev Portal Service deprecation](https://wiki.atl.workiva.net/display/DE/Poster+-+Dev+Portal+Discovery+2.0%3A+Discovery+and+Planning); 
we are deprecating the “docs.yml” file that’s been created to render repo markdown files on to the portal.
File paths included in docs.yml of this repo will no longer be rendered/hosted on
[Dev Portal](https://dev.workiva.net/docs/) with the yml file deletion.
Please reach out to `#support-dev-portal` or `#support-developer-efficiency` with any questions.
[_Created by Sourcegraph batch change `Workiva/remove_docs_yml`._](https://sourcegraph.wk-dev.wdesk.org/organizations/Workiva/batch-changes/remove_docs_yml)

DE-633: Delete docs.yml file created for Dev Portal.

---

pubspec.yaml

Summary
---
Client Platform is updating dependencies! Read more details at
https://wiki.atl.workiva.net/display/CP/Dependency+Upgrades
This batch is to find and open PRs to upgrade dependency_validator to v2.
Additional manual work that might be needed (CP will do):
[ ] Run dependency_validator to repos that aren't running it,
but do have the dependency. 
[ ] Fix CI due to removing an ignore that was actually needed.
For more info, reach out to `#support-client-plat` on Slack.
[_Created by Sourcegraph batch change `Workiva/update_dep_validator`._](https://sourcegraph.wk-dev.wdesk.org/organizations/Workiva/batch-changes/update_dep_validator)

Upgrade dependency_validator

---

skynet.yaml

Currently release pipelines are failing because they require a skynet run in order to pass the testing phase of the pipeline. We would like to not have to manually check that the github workflow passed and override the pipeline so we need a way to automatically check that the workflow passed and tell the pipeline that all is good.
Add a skynet.yaml that checks the github workflow run and passes or fails the skynet run depending on the results.
Add skynet run to check that the github workflow run passes

FW-145 Add skynet config that verifies github workflow passes

---

CHANGELOG.md
pubspec.yaml

We can safely widen this package's dependency on analyzer to include v2 without breaking anything. It resolves to v2 on Dart 2.13.4 and all tests and analysis pass.

FEA-895 Widen analyzer range to include v2

---

.github/workflows/dart_ci.yaml
Dockerfile

Summary
---
This batch overrides the docker images used to equivalent Dart 2.18 versions.
The goal is to run as many CI runs across the dart ecosystem as possible on 
Dart 2.18 to find and fix errors before releasing a production 2.18 image.
For more info, reach out to `#support-frontend-dx` on Slack.
[_Created by Sourcegraph batch change `Workiva/test_dart_218`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/test_dart_218)

Test Dart 2.18

---

.github/workflows/dart_ci.yaml
pubspec.yaml

We want to unblock analyzer 6, so open the range to allow it.
While in here, remove the dependency on dependency_validator 3 and install and run it globally instead.

Allow analyzer 6

---

pubspec.yaml

The latest [analyzer](https://pub.dev/packages/analyzer) version is 7.x, and this package only allows <7, preventing downstream packages from pulling that in.
- Raise upper bound of analyzer
- Update SDK constraint to allow Dart 3, since we already support it and run CI against Dart 3
Verify CI passes in Dart 3, and pulls in analyzer 7 (looks like it is [here](https://github.com/Workiva/dart_transformer_utils/actions/runs/15932070625/job/44943359172#step:4:11))

FED-3969 Allow analyzer 7.x, explicitly support Dart 3

---

CHANGELOG.md
pubspec.yaml

Pull Requests included in release:
* Patch changes:
* [FED-3969 Allow analyzer 7.x, explicitly support Dart 3](https://github.com/Workiva/dart_transformer_utils/pull/77)
Requested by: @greglittlefield-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_transformer_utils/compare/0.2.22...Workiva:release_dart_transformer_utils_0.2.23
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_transformer_utils/compare/0.2.22...0.2.23
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/5977371284340736/logs/)
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5977371284340736/?repo_name=Workiva%2Fdart_transformer_utils&pul …

RM-302017 Release dart_transformer_utils 0.2.23
